server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: pig
    password: ENC(gc16brBHPNq27HsjaULgKGq00Rz6ZUji)
    url: jdbc:mysql://127.0.0.1:3306/technode_dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true


zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      password: chenby
      username: cby19881205
      queue: zipkin
  storage:
    type: mysql