server:
  port: 9999

spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: pig-auth,pig-upms-service,pig-demo-service,pig-account-center,account-center
  ignoredServices: '*'
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ratelimit:
    key-prefix: pig-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      pig-upms-service:
        limit: 100
        quota: 100
        refresh-interval: 3
      pig-account-center:
        limit: 100
        quota: 100
        refresh-interval: 3
  routes:
    pig-auth:
      path: /account/**
      serviceId: pig-account-center
      stripPrefix: true
      sensitiveHeaders:
security:
  validate:
    code: true
    preview: false
  sessions: stateless
  oauth2:
    client:
      client-id: pig
      client-secret: pig
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token
      service-id: pig-gateway
      jwt:
         key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

ignore:
  urls:
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/user/register
    - /admin/user/send/checkRegisterEmail/*
    - /admin/user/send/register/email/*
    - /account/code/*
    - /account/center/forget/password/*
    - /account/center/send/forgetPasswordEmail   
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/userMenu
    - /swagger-resources/**
    - /account/swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
    - /css/**
  clients:
    - app